---
layout: cv
title: Tyler Danley's CV
---

Accounting Student.


<a href="tylerdanley3@gmail.com">tylerdanley3@gmail.com</a>
| <a href="https://www.linkedin.com/in/tyler-danley/">My LinkedIn page</a>
</div>


## Currently

Motivated college student eager to expand professional knowledge 
and contribute positively to work environment. Well-organized, 
reliable, and proficient in computer software and customer service. 
Articulate communicator and strong collaborator with high-achieving 
planning and problem-solving abilities

### Specialized in

Clear Insights
April 2025 - Present
Rexburg, Idaho
 Conducted over a hundred outbound calls per shift to gather 
customer insights for major market research projects
 Increased project requirements by 200% through building 
connections with individuals and fostering a clear understanding 
of research
 Received high remarks in all aspects when rated by supervisors 
and management ranked in 96th percentile


Volunteer Representative
The Church Of Jesus Christ Of Latter-day 
Saints
April 2023 - March 2025
Atlanta, Georgia
 Spent twelve hours daily teaching, going door-to-door, studying, 
and doing community service for people in Northern Georgia
 Volunteered every week by serving in food banks, soup kitchens, 
and thrift stores
 Collaborated closely with sixteen other missionaries to achieve 
daily goals by expanding outreach and engaging with new 
individuals



## Education

Bachelor of Science
Brigham Young University - 
Idaho
April 2025 - April 2027
 Current GPA: 3.70
 Currently pursuing a 
bachelor's degree in 
accounting

Associate of Arts
Idaho State University
August 2019 - June 2021
 Received an associate's 
degree in general studies 
while in high school




## Skills

 Customer Service - 
Experience in working with 
customers, including sales 
and customer care

 Leadership - Demonstrated 
experience in leading and 
mentoring peers to 
accomplish objectives

 Hardworking - Volunteered 
two years of daily diligent 
work requiring constant 
effort and dedication to 
achieve goals

 Financial Accounting – 
Knowledge of preparing and 
analyzing financial 
statements including income 
statements, balance sheets, 
cash flow statements

 Programming – Familiar with 
Python for data 
manipulation, simple 
automation, and scripting 
tasks





<!-- ### Footer

Last updated: December 2025 -->